### PR TITLE
Updated remote modal

### PR DESCRIPTION
**Pull request by cabidop**
This is a revamp of the remote modal to include the following changes:
- Removal of the deprecation warnings according to [this guide](https://meta.discourse.org/t/converting-modals-from-legacy-controllers-to-new-dmodal-component-api/268057) (similar approach as with the "import page" modal in #11)
- Simplification of the component flow by using the `buffered-content` Discourse mixin instead of a custom implementation.
- Addition of a reset button to remove the remote configuration if it exists (only EmberJS code as the Rails endpoint was already present).

### CODE REVIEW

**Comment by angusmcleod** [comment]
@cabidop Looks good! The only (minor) thing I'm noticing is that the addition of the reset button means that the modal footer is not quite wide enough to accommodate the loading spinner without expanding slightly when it appears. The width of the modal shouldn't change.

https://www.loom.com/share/7f437bdd20214cb29d1ba280b10015f0

**Review by angusmcleod — CHANGES_REQUESTED** [review]
@cabidop Looks good! The only (minor) thing I'm noticing is that the addition of the reset button means that the modal footer is not quite wide enough to accommodate the loading spinner without expanding slightly when it appears. The width of the modal shouldn't change.

https://www.loom.com/share/7f437bdd20214cb29d1ba280b10015f0

**Comment by angusmcleod** [comment]
@cabidop I'm being pedantic I know, but the cancel button is moving now :)

https://www.loom.com/share/16274d86c37d43e29f3c598e3a6b67fb

Perhaps we can align that on the right of the footer? Just visually it doesn't look great when other elements are moved by a loading spinner. Sorry to be so picky. You seem on top of things though, so I think you can handle being held to a high standard.

**Comment by cabidop** [comment]
No worries, @angusmcleod! It was actually another "broken" style from the modal upgrade so the cancel button should be properly aligned now.

**Review by angusmcleod — APPROVED** [review]
@cabidop Looks good 👍

**Pull request merged**
